language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
cache:
  directories:
  - $HOME/.composer/cache/files
before_install:
- composer install
install:
- openssl aes-256-cbc -K $encrypted_c2c0feadb429_key -iv $encrypted_c2c0feadb429_iv -in ./travis-ci/accounts.enc -out ./travis-ci/accounts.json -d
script: 
- vendor/bin/phpunit tests --colors=always --verbose --debug

