<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;
use SquareConnect\Model\Money;
use SquareConnect\Model\AdditionalRecipient;
use SquareConnect\Model\AdditionalRecipientTest;

/**
 * RefundTest Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://squareup.com/developers
 */
class RefundTest extends \PHPUnit_Framework_TestCase
{

    private static $refund;

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {
        self::$refund = new \SquareConnect\Model\Refund();
    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test Refund
     */
    public function testRefund() {

    }

    /**
     * Test AdditionalRecipients
     */
    public function testAdditionalRecipients() {
        $recipient = [
            "location_id" => "location",
            "description" => "description",
            "amount_money" => [
              "amount" => 1,
              "currency" => "USD"
            ]
        ];
        self::$refund->setAdditionalRecipients([$recipient]);
        $this->assertContains($recipient, self::$refund->getAdditionalRecipients());
    }

}
