<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace SquareConnect\Api;

use \SquareConnect\Configuration;
use \SquareConnect\ApiClient;
use \SquareConnect\ApiException;
use \SquareConnect\ObjectSerializer;

/**
 * CashDrawersApiTest Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://squareup.com/developers
 */
class CashDrawersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test case for listCashDrawerShiftEvents
     *
     * ListCashDrawerShiftEvents
     *
     */
    public function test_listCashDrawerShiftEvents() {

    }
    /**
     * Test case for listCashDrawerShifts
     *
     * ListCashDrawerShifts
     *
     */
    public function test_listCashDrawerShifts() {

    }
    /**
     * Test case for retrieveCashDrawerShift
     *
     * RetrieveCashDrawerShift
     *
     */
    public function test_retrieveCashDrawerShift() {

    }
}
