<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace SquareConnect\Api;

use \SquareConnect\Configuration;
use \SquareConnect\ApiClient;
use \SquareConnect\ApiException;
use \SquareConnect\ObjectSerializer;

/**
 * CustomerGroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://squareup.com/developers
 */
class CustomerGroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test case for createCustomerGroup
     *
     * CreateCustomerGroup
     *
     */
    public function test_createCustomerGroup() {

    }
    /**
     * Test case for deleteCustomerGroup
     *
     * DeleteCustomerGroup
     *
     */
    public function test_deleteCustomerGroup() {

    }
    /**
     * Test case for listCustomerGroups
     *
     * ListCustomerGroups
     *
     */
    public function test_listCustomerGroups() {

    }
    /**
     * Test case for retrieveCustomerGroup
     *
     * RetrieveCustomerGroup
     *
     */
    public function test_retrieveCustomerGroup() {

    }
    /**
     * Test case for updateCustomerGroup
     *
     * UpdateCustomerGroup
     *
     */
    public function test_updateCustomerGroup() {

    }
}
