<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace SquareConnect\Api;

use \SquareConnect\Configuration;
use \SquareConnect\ApiClient;
use \SquareConnect\ApiException;
use \SquareConnect\ObjectSerializer;

/**
 * LaborApiTest Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://squareup.com/developers
 */
class LaborApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test case for createBreakType
     *
     * CreateBreakType
     *
     */
    public function test_createBreakType() {

    }
    /**
     * Test case for createShift
     *
     * CreateShift
     *
     */
    public function test_createShift() {

    }
    /**
     * Test case for deleteBreakType
     *
     * DeleteBreakType
     *
     */
    public function test_deleteBreakType() {

    }
    /**
     * Test case for deleteShift
     *
     * DeleteShift
     *
     */
    public function test_deleteShift() {

    }
    /**
     * Test case for getBreakType
     *
     * GetBreakType
     *
     */
    public function test_getBreakType() {

    }
    /**
     * Test case for getEmployeeWage
     *
     * GetEmployeeWage
     *
     */
    public function test_getEmployeeWage() {

    }
    /**
     * Test case for getShift
     *
     * GetShift
     *
     */
    public function test_getShift() {

    }
    /**
     * Test case for listBreakTypes
     *
     * ListBreakTypes
     *
     */
    public function test_listBreakTypes() {

    }
    /**
     * Test case for listEmployeeWages
     *
     * ListEmployeeWages
     *
     */
    public function test_listEmployeeWages() {

    }
    /**
     * Test case for listWorkweekConfigs
     *
     * ListWorkweekConfigs
     *
     */
    public function test_listWorkweekConfigs() {

    }
    /**
     * Test case for searchShifts
     *
     * SearchShifts
     *
     */
    public function test_searchShifts() {

    }
    /**
     * Test case for updateBreakType
     *
     * UpdateBreakType
     *
     */
    public function test_updateBreakType() {

    }
    /**
     * Test case for updateShift
     *
     * UpdateShift
     *
     */
    public function test_updateShift() {

    }
    /**
     * Test case for updateWorkweekConfig
     *
     * UpdateWorkweekConfig
     *
     */
    public function test_updateWorkweekConfig() {

    }
}
