<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace SquareConnect\Api;

use \SquareConnect\Configuration;
use \SquareConnect\ApiClient;
use \SquareConnect\ApiException;
use \SquareConnect\ObjectSerializer;

/**
 * TerminalApiTest Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://squareup.com/developers
 */
class TerminalApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    /**
     * Test case for cancelTerminalCheckout
     *
     * CancelTerminalCheckout
     *
     */
    public function test_cancelTerminalCheckout() {

    }
    /**
     * Test case for createTerminalCheckout
     *
     * CreateTerminalCheckout
     *
     */
    public function test_createTerminalCheckout() {

    }
    /**
     * Test case for getTerminalCheckout
     *
     * GetTerminalCheckout
     *
     */
    public function test_getTerminalCheckout() {

    }
    /**
     * Test case for searchTerminalCheckouts
     *
     * SearchTerminalCheckouts
     *
     */
    public function test_searchTerminalCheckouts() {

    }
}
